#!/usr/bin/env bash
# Drives the real app in a real browser, in demo mode.
#
#   ./test/run-tests.sh
#
# Needs Playwright available to node (npm i -g playwright, or set NODE_PATH).
# Set CHROME_PATH if Playwright can't find a browser on its own.
#
# flow.test.mjs   — the approval loop: mark done, undo, reject, redo, approve,
#                   pay out. Asserts that marking done alone never earns money.
# config.test.mjs — the parent editors: add/edit/re-price a chore, add a child,
#                   change currency, and the PIN lockout.

set -euo pipefail

PORT=${PORT:-8765}
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"

export BASE_URL="http://localhost:$PORT"
export SHOT_DIR="${SHOT_DIR:-$ROOT/.test-screenshots}"

# Two runs on one port is a confusing way to fail: the second serves nothing,
# and when the FIRST finishes its cleanup tears the server out from under the
# second, which then dies mid-suite on ERR_CONNECTION_REFUSED and looks for all
# the world like a real regression. Say what actually happened instead.
# (The database runner refuses the same way.)
if curl -fsS "$BASE_URL/index.html" >/dev/null 2>&1; then
  echo "Something is already serving on port $PORT — is another test run going?" >&2
  echo "Stop it, or re-run with PORT=8799 ./test/run-tests.sh" >&2
  exit 1
fi

# Playwright is usually installed globally; make it importable either way.
if [ -z "${NODE_PATH:-}" ] && [ -d /opt/node22/lib/node_modules ]; then
  export NODE_PATH=/opt/node22/lib/node_modules
fi

# Serve a COPY of the app with config.js forced to demo mode.
#
# Once you've filled in config.js with your own Supabase project, the real app
# no longer runs on localStorage — so tests run against the live app would need
# your credentials, would depend on whatever state your real database happens
# to be in, and would write test chores into your family's actual data. Copying
# to a scratch directory keeps the suite hermetic and keeps your config
# untouched.
STAGE="$(mktemp -d)"
trap 'kill ${SERVER:-0} 2>/dev/null || true; rm -rf "$STAGE"' EXIT

tar -C "$ROOT" --exclude=.git --exclude=node_modules --exclude=.test-screenshots -cf - . \
  | tar -C "$STAGE" -xf -

cat > "$STAGE/config.js" <<'DEMO'
// Generated by test/run-tests.sh — demo mode so the suite never touches a real
// Supabase project. The repo's own config.js is not modified.
export const CONFIG = {
  mode: 'local',
  supabaseUrl: '',
  supabaseAnonKey: '',
  vapidPublicKey: '',
};
DEMO

echo "==> serving a demo-mode copy on port $PORT"
python3 -m http.server "$PORT" --directory "$STAGE" >/dev/null 2>&1 &
SERVER=$!

# Wait for the server rather than sleeping a fixed amount.
for _ in $(seq 1 40); do
  if curl -fsS "$BASE_URL/index.html" >/dev/null 2>&1; then break; fi
  sleep 0.25
done

echo "==> stats arithmetic"
node "$HERE/stats.test.mjs"

echo
echo "==> config URL handling"
node "$HERE/url.test.mjs"

echo
echo "==> renaming children"
node "$HERE/rename.test.mjs"

echo
echo "==> reassigning a chore"
node "$HERE/reassign.test.mjs"

echo
echo "==> the parent's week navigation staying on the parent's screen"
node "$HERE/week-leak.test.mjs"

echo
echo "==> paging through weeks in the schedule"
node "$HERE/week-nav.test.mjs"

echo
echo "==> two chores sharing a name"
node "$HERE/duplicate-name.test.mjs"

echo
echo "==> marking someone away"
node "$HERE/away.test.mjs"

echo
echo "==> savings goals"
node "$HERE/goals.test.mjs"

echo
echo "==> streaks"
node "$HERE/streak.test.mjs"

echo
echo "==> bonus chores"
node "$HERE/bonus.test.mjs"

echo
echo "==> downloading a backup"
node "$HERE/export.test.mjs"

echo
echo "==> approval flow"
node "$HERE/flow.test.mjs"

echo
echo "==> expired chores"
node "$HERE/expired.test.mjs"

echo
echo "==> fresh start"
node "$HERE/fresh-start.test.mjs"

echo
echo "==> undoing an approval"
node "$HERE/undo-approval.test.mjs"

echo
echo "==> parent dashboard"
node "$HERE/dashboard.test.mjs"

echo
echo "==> configuration"
node "$HERE/config.test.mjs"

echo
echo "==> screenshots in $SHOT_DIR"
